version: '3.7'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  app:
   image: aplicacion
   depends_on:
     - bd
   environment:
     SECRET_KEY: ${SECRET_KEY}
     BD_NAME: ${BD_NAME}
     BD_USER: ${BD_USER}
     BD_PASSWORD: ${BD_PASSWORD}
     BD_HOST: ${BD_HOST}
     BD_PORT: ${BD_PORT}
     RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
     RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
     TOKEN_T: ${TOKEN_T}
     CHAT_ID: ${CHAT_ID}
   volumes:
     - ./Proyecto/proyecto:/code
   deploy:
     resources:
        limits:
            cpus: "1"
            memory: "1024M"

  bd:
   image: mariadb
   restart: always
   environment:
    MYSQL_DATABASE: ${BD_NAME}
    MYSQL_USER: ${BD_USER}
    MYSQL_PASSWORD: ${BD_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${BD_ROOT_PASS}
   volumes:
    - ./data:/var/lib/mysql
   deploy:
     resources:
        limits:
            cpus: "1"
            memory: "1024M"

  nginx:
   image: nginx
   restart: always
   ports:
    - 443:443
    - 80:80
   volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./proyecto/static:/static
    - ./certificados:/certs
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
   deploy:
     resources:
        limits:
            cpus: "1"
            memory: "1024M"


volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
