# Generated by Django 4.2.16 on 2025-05-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('salt_passwd', models.BinaryField(default=b'')),
                ('passwd', models.CharField(max_length=129)),
            ],
        ),
    ]
