# Generated by Django 5.1.7 on 2025-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='salt',
            field=models.BinaryField(max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='passwd',
            field=models.CharField(max_length=60),
        ),
    ]
