# Generated by Django 5.1.7 on 2025-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_administrador_salt_alter_administrador_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='passwd',
        ),
        migrations.AddField(
            model_name='administrador',
            name='passwdHash',
            field=models.BinaryField(max_length=60, null=True),
        ),
    ]
