# Generated by Django 5.1.7 on 2025-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_remove_administrador_passwd_administrador_passwdhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='passwdHash',
            field=models.BinaryField(default=b'', max_length=60),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='salt',
            field=models.BinaryField(default=b'', max_length=29),
        ),
    ]
